### ISSUE TITLE
unrecognized arguments: --run-id : static-rid with --run-id cli option 

### ISSUE THREAD

**Issue by ChandraMouliDisturbs** [rahul-verma/arjuna#5]
Given the following command 
`python arjuna_launcher.py run-project --static-rid --run-id l5434`

Arjuna is throwing  the following error on console
```
-------------------------------------------------
Arjuna
Version: 0.9.20
Creator: Rahul Verma
(c) 2015-2020 Rahul Verma
www.RahulVerma.net
-------------------------------------------------
Parsing CLI Options...
Intializing Arjuna...
usage: python -m arjuna [-h] [-dl {TRACE,DEBUG,INFO,WARN,ERROR,FATAL}]
                        [-ll {TRACE,DEBUG,INFO,WARN,ERROR,FATAL}]
                        {create-project,run-project,run-selected} ...
python -m arjuna: error: unrecognized arguments: --run-id l5434
```
**Expected:** Arjuna to create a directory under reports with name l5434.

**Comment by rahul-verma** [comment]
The switch is --runid not --run-id in 0.9.20. You can try -h option with a command to see exact switches e.g.  python arjuna_launcher.py run-project --static-rid --run-id l5434 -h. 

However, as it is inconsistent with rest of the run switches, in 0.9.21 it is changed to --run-id.
Change gone in https://github.com/rahul-verma/arjuna/commit/0c385d15b1ef4c1109b0bc0a38a967893c6b5910.
